name: Build master

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v2.4.0

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Get dependencies and run test
        run: |
          go test ./...

      - name: gen go-bindata
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          go get -u github.com/go-bindata/go-bindata/...
          go-bindata -o internal/bindata/geoip/geoip.go -pkg bingeoip  assets/GeoLite2-City.mmdb assets/flags.json

      - name: Build
        uses: crazy-max/ghaction-xgo@v1.6.1
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: 1.17
          dest: dist
          prefix: proxypool
          targets: linux/amd64,linux/386,linux/arm-5,linux/arm-7,linux/arm64,linux/s390x,linux/mipsle,darwin-10.12/amd64,darwin-10.12/arm64,windows-6.0/amd64,windows-6.0/386
          ldflags: -w -s -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: /

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
