name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies and run test
        run: |
          go test ./...

      - name: gen go-bindata
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          go get -u github.com/go-bindata/go-bindata/...
          go-bindata -o internal/bindata/geoip/geoip.go -pkg bingeoip  assets/GeoLite2-City.mmdb assets/flags.json

      - name: Build (tun)
        uses: crazy-max/ghaction-xgo@v1.6.1
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: 1.17
          dest: dist
          prefix: proxypool
          targets: linux/amd64,linux/386,linux/arm-5,linux/arm-7,linux/arm64,linux/mipsle,darwin-10.12/amd64,darwin-10.12/arm64,windows-6.0/amd64,windows-6.0/386
          ldflags: -w -s -X main.appVersion=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: cmd

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/proxypool-linux-amd64
            ./dist/proxypool-linux-386
            ./dist/proxypool-linux-arm-5
            ./dist/proxypool-linux-arm-7
            ./dist/proxypool-linux-arm64
            ./dist/proxypool-linux-mipsle
            ./dist/proxypool-linux-s390x
            ./dist/proxypool-darwin-10.12-amd64
            ./dist/proxypool-darwin-10.12-arm64
            ./dist/proxypool-windows-6.0-amd64.exe
            ./dist/proxypool-windows-6.0-386.exe

